SELECT TOP (1000) [id]
      ,[username]
      ,[birth_year]
      ,[gender]
      ,[email]
      ,[hashed_password]
      ,[avatar_path]
      ,[adress]
      ,[status]
      ,[create_at]
      ,[update_at]
      ,[delete-at]
  FROM [FoodSystem].[dbo].[user]
